const express=require('express');
const rateLimit=require('express-rate-limit');
const router=express.Router();
const ctrl=require('../controllers/auth.controller');
const {verifyToken,requireRole}=require('../middlewares/auth.middleware');
const authLimiter=rateLimit({windowMs:15*60*1000,max:5,standardHeaders:true,legacyHeaders:false,message:{success:false,message:'Demasiados intentos. Intenta nuevamente en 15 minutos.'}});
router.post('/login',authLimiter,ctrl.login);
router.post('/register',ctrl.register);
router.post('/password-reset/request',authLimiter,ctrl.requestPasswordReset);
router.post('/password-reset/confirm',ctrl.resetPassword);
router.post('/users',verifyToken,requireRole('Administrador'),ctrl.createUserByAdmin);
module.exports=router;
